on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Configure AWS credentials using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::376129867238:role/github-actions-role
          aws-region: us-east-1

      # Login to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin 376129867238.dkr.ecr.us-east-1.amazonaws.com

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ecommerce-app:${{ github.sha }} .

      # Tag image for ECR
      - name: Tag image for ECR
        run: |
          docker tag ecommerce-app:${{ github.sha }} \
          376129867238.dkr.ecr.us-east-1.amazonaws.com/ecommerce-app:${{ github.sha }}

      # Push Docker image to ECR
      - name: Push image to ECR
        run: |
          docker push 376129867238.dkr.ecr.us-east-1.amazonaws.com/ecommerce-app:${{ github.sha }}

      # Wait for any ongoing instance refresh to finish
      - name: Wait for previous ASG refresh
        run: |
          ASG_NAME="terraform-20260224164242658500000010"
          while aws autoscaling describe-instance-refreshes \
                  --auto-scaling-group-name $ASG_NAME \
                  --query 'InstanceRefreshes[?Status==`InProgress`]' \
                  | grep -q .; do
              echo "Instance refresh in progress, waiting 60 seconds..."
              sleep 60
          done

      # Trigger Auto Scaling Group refresh
      - name: Trigger ASG refresh
        run: |
          aws autoscaling start-instance-refresh \
              --auto-scaling-group-name terraform-20260224164242658500000010
